# SPDX-FileCopyrightText: 2026 Niels Franke
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Promote curated picks from the download pool into the committed demo asset set.

Reads demo/assets/_pool/ (produced by fetch_assets.py), copies the hand-selected files into
demo/assets/<group>/NN.jpg, and regenerates demo/assets/CREDITS.md from the recorded CC0
attribution. The _pool/ dir is throwaway (gitignored) — only the selection is committed.

Run:  backend/.venv/bin/python demo/select_assets.py
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
POOL = HERE / "assets" / "_pool"
ASSETS = HERE / "assets"

# group -> ordered list of pool keys (category/filename) to promote.
SELECTION: dict[str, list[str]] = {
    "iceland": [
        "iceland/iceland-00.jpg", "iceland/iceland-01.jpg", "iceland/iceland-02.jpg",
        "iceland/iceland-04.jpg", "iceland/iceland-07.jpg",
    ],
    "editorial": [
        "editorial/editorial-00.jpg", "editorial/editorial-01.jpg", "editorial/editorial-02.jpg",
        "editorial/editorial-03.jpg", "editorial/editorial-04.jpg", "editorial/editorial-05.jpg",
        "editorial/editorial-06.jpg", "editorial/editorial-07.jpg",
    ],
    "coastal": [
        "coastal/coastal-00.jpg", "coastal/coastal-01.jpg", "coastal/coastal-02.jpg",
        "coastal/coastal-03.jpg", "coastal/coastal-05.jpg", "coastal/coastal-06.jpg",
        "coastal/coastal-07.jpg",
    ],
    "studio": ["architecture/architecture-00.jpg", "architecture/architecture-04.jpg"],
    "location": ["architecture/architecture-05.jpg", "architecture/architecture-07.jpg"],
}


def main() -> None:
    meta = json.loads((POOL / "meta.json").read_text())
    credits: list[str] = [
        "# Demo photo credits",
        "",
        "All photos below are licensed **CC0 1.0** (public domain dedication) and were sourced via",
        "[Openverse](https://openverse.org/). They are placeholder content for the documentation",
        "screenshots only. Generated by `demo/select_assets.py`.",
        "",
    ]
    for group, keys in SELECTION.items():
        dest = ASSETS / group
        # clean previous selection so reruns are deterministic
        if dest.exists():
            for f in dest.glob("*.jpg"):
                f.unlink()
        dest.mkdir(parents=True, exist_ok=True)
        credits.append(f"## {group}")
        credits.append("")
        for i, key in enumerate(keys):
            src = POOL / key
            out_name = f"{i:02d}.jpg"
            shutil.copyfile(src, dest / out_name)
            m = meta.get(key, {})
            title = m.get("title") or "Untitled"
            creator = m.get("creator") or "Unknown"
            landing = m.get("foreign_landing_url") or ""
            src_name = m.get("source") or "openverse"
            credits.append(
                f"- `{group}/{out_name}` — \"{title}\" by {creator} "
                f"({src_name}, CC0){' — ' + landing if landing else ''}"
            )
        credits.append("")
        print(f"{group}: {len(keys)} files")

    (ASSETS / "CREDITS.md").write_text("\n".join(credits))
    print(f"\nWrote {ASSETS / 'CREDITS.md'}")


if __name__ == "__main__":
    main()
