# SPDX-FileCopyrightText: 2026 Niels Franke
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Promote hand-picked candidates from the download pool into the committed demo asset set.

Reads demo/assets/_pool/ (from fetch_assets.py), copies the selected files into
demo/assets/<group>/NN.jpg, and regenerates demo/assets/CREDITS.md. The _pool/ dir is throwaway
(gitignored) — only the selection is committed.

Run:  backend/.venv/bin/python demo/select_assets.py
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
POOL = HERE / "assets" / "_pool"
ASSETS = HERE / "assets"

# group -> ordered pool indices (filenames NN.jpg) to promote. The early picsum ids (0-9) are
# the well-worn "laptop on a desk" stock shots — deliberately excluded.
SELECTION: dict[str, list[int]] = {
    "coastal": [12, 13, 14, 15, 16, 34, 35],
    "iceland": [10, 11, 17, 27, 28],
    "editorial": [18, 19, 23, 24, 31, 36, 37, 38],
    "studio": [29, 39],
    "location": [22, 26],
}


def main() -> None:
    meta = json.loads((POOL / "meta.json").read_text())
    credits = [
        "# Demo photo credits",
        "",
        "Placeholder photos are served by [Lorem Picsum](https://picsum.photos/), which sources",
        "them from [Unsplash](https://unsplash.com/) under the",
        "[Unsplash License](https://unsplash.com/license) (free to use, no attribution required).",
        "They are placeholder content for the documentation screenshots only. Generated by",
        "`demo/select_assets.py`.",
        "",
    ]
    for group, idxs in SELECTION.items():
        dest = ASSETS / group
        if dest.exists():
            for f in dest.glob("*.jpg"):
                f.unlink()
        dest.mkdir(parents=True, exist_ok=True)
        credits.append(f"## {group}")
        credits.append("")
        for i, idx in enumerate(idxs):
            src_name = f"{idx:02d}.jpg"
            out_name = f"{i:02d}.jpg"
            shutil.copyfile(POOL / src_name, dest / out_name)
            m = meta.get(src_name, {})
            author = m.get("author") or "Unknown"
            url = m.get("url") or ""
            credits.append(
                f"- `{group}/{out_name}` — by {author} (Unsplash via Lorem Picsum"
                f"{', ' + url if url else ''})"
            )
        credits.append("")
        print(f"{group}: {len(idxs)} files")

    (ASSETS / "CREDITS.md").write_text("\n".join(credits))
    print(f"\nWrote {ASSETS / 'CREDITS.md'}")


if __name__ == "__main__":
    main()
